### ISSUE TITLE
[Bypass] ElytraFly

### ISSUE THREAD

**Issue by dkim19375** [Elikill58/Negativity#184]
**Describe the bug**
No checks with ElytraFly. Hack clients tested: Sigma5, SalHack. Also, Regular flyhacks don't get caught when using an elytra.

**Your plugin version**
Negativity 1.9.5

**Your platform version (and precise the platforme (spigot/sponge))**
Paper
Minecraft 1.15.2
Client 1.12.2, 1.15.2

**Screenshots**
![image](https://user-images.githubusercontent.com/65050767/94995579-44df6f80-056d-11eb-8942-7a306693f9c7.png)
![image](https://user-images.githubusercontent.com/65050767/94995584-4a3cba00-056d-11eb-8646-1bcf6f75b4e0.png)
![image](https://user-images.githubusercontent.com/65050767/94995588-4d37aa80-056d-11eb-93e0-7b2cdbfd4518.png)
![image](https://user-images.githubusercontent.com/65050767/94995592-50329b00-056d-11eb-8de4-ec1613828537.png)
![image](https://user-images.githubusercontent.com/65050767/94995595-545eb880-056d-11eb-9931-461ce5d552f0.png)
^^ The 91 is my fps
![image](https://user-images.githubusercontent.com/65050767/94995601-5aed3000-056d-11eb-96d5-e551905b5693.png)

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).

**Additional context**

**Comment by Elikill58** [comment]
Can you show me a video ?

**Comment by dkim19375** [comment]
Sure, one sec

**Comment by dkim19375** [comment]
https://i.imgur.com/jhsg31t.mp4

**Comment by Elikill58** [comment]
Fixed in v2.
I don't know if I have to put this detection on v1 (free).

**Comment by dkim19375** [comment]
Still occuring; not fixed, regular fly works (to make sure that the anticheat is working), but elytrafly is still bypassing

**Comment by dkim19375** [comment]
I'll close this and make a new issue (and mark it as a bug please)
