### ISSUE TITLE
Server logs getting spamed with this:

### ISSUE THREAD

**Issue by Krater107a** [Elikill58/Negativity#270]
**Describe the bug**
Log files are filling up with this:

**Your plugin version**
1.10

**Your server version (and the software type (spigot/sponge))**
Minecraft 1.17 using spigot-paper build 17

**Screenshots**

**Error / Logs**
https://gist.github.com/Krater107a/8e02b6ad0f1f51374f9d047d4db5b27b

**Additional context**
Looks like a nice anti cheat, hope these issues can get resolved! :D

**Comment by ten1ser** [comment]
Have the same warning right now, 
Server version using: Purpur 1.17
https://pastebin.com/Ldtmubnz

**Comment by Elikill58** [comment]
It's not the same issue.

He have error when receiving packet and you it's when registering it

**Comment by Elikill58** [comment]
@Krater107a The error seems to be fixed since new build. I didn't get it with new, and after checking latest changelog, it seems to add new patch to spigot for it. But, I will make few change to prevent this possible issue.

This issue keep open for the @ten1ser issue, which seems near to the basic one, even if it's not the same.

**Comment by ten1ser** [comment]
Thanks

**Comment by Krater107a** [comment]
Thankyou, as soon as this version becomes available I will test and report back.

**Comment by Krater107a** [comment]
Ok, after updating negativity to the latest release, am still getting an error thrown a little bit after anyone logs on to server. See attached gist for error: https://gist.github.com/Krater107a/aefb9b7c14448176a45fe591a473af3b

**Comment by Elikill58** [comment]
Did you download the jar after yesterday at 7PM ?
The error seems to appear with ProtocolLib, and have been fixed with a ghost update

**Comment by Krater107a** [comment]
The jar I downloaded is from spigot's repository, posted Monday, June 28th, labeled as version "1.10". I am using ProtocolLib v4.7.0-SNAPSHOT-b526. Unfortunately, am still getting the error when ever anyone logs in to server. 

"[13:37:47] [Server thread/ERROR]: Could not pass event PacketReceiveEvent to Negativity v1.10
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "type" is null"
